### ISSUE TITLE
Make mobile responsive home page

### ISSUE THREAD

**Issue by liambrewster** [lgope/Natours#29]
I clicked your your website and this is what I was greeted with ,

![image](https://user-images.githubusercontent.com/31896214/132911172-5efa45a9-81ac-4a0c-955e-bf256ec3bf7f.png)

**Comment by lgope** [comment]
> I clicked your your website and this is what I was greeted with ,
> 
> ![image](https://user-images.githubusercontent.com/31896214/132911172-5efa45a9-81ac-4a0c-955e-bf256ec3bf7f.png)

Thanks for your feedback. I am working on it.
